### ISSUE TITLE
Add GitLab support

### ISSUE THREAD

**Issue by CameronBanga** [DoWhileGeek/open-repo#2]
Tried the project out with GitLab. Looking at your code, the pattern seems like it should work, but getting "Could not parse remote url" when I attempt with a GitLab URL.

Any chance to add this?

**Comment by DoWhileGeek** [comment]
I've never worked with gitlab before, I dont know what their uri's look like. If you can share the output of `git remote -v`, and the actual homepage of the remote, I'll add support.

**Comment by DoWhileGeek** [comment]
Closing this as I cannot reproduce.

**Comment by CameronBanga** [comment]
I had forgotten all about this ticket and app, but just downloaded it and tested.

Can confirm, it works now!

**Comment by DoWhileGeek** [comment]
🙌
